import './globals.css'
import { AuthProvider } from '@/contexts/modals'

export const metadata = {
  title: 'ERP-Lab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
